### ISSUE TITLE
Materialize Button

### ISSUE THREAD

**Issue by rich-strain** [rich-strain/cocktail-search#12]
Research Materialize CSS buttons and modals. You'll need to know how they are initialized, closed and opened. You may also want to research the different styles for the buttons as well.

**Comment by Mattw05** [comment]
materialize getting started - https://materializecss.com/getting-started.html
materialize css link - https://materializecss.com/buttons.html

**Comment by Mattw05** [comment]
https://materializecss.com/modals.html
